default_platform(:ios)
import("./Certificates")

platform :ios do
  key_id = ENV['APP_STORE_CONNECT_KEY_ID']
  issuer_id = ENV['APP_STORE_CONNECT_ISSUER_ID']
  key_content = ENV['APP_STORE_CONNECT_KEY']

  lane :tests do
    run_tests(scheme: "PIA VPN")
  end

  lane :tvOStests do
    run_tests(scheme: "PIA VPN-tvOS")
  end

  lane :ios_e2e_tests do
    # build_app(
    #   scheme: "PIA VPN dev", 
    #   skip_archive: true,
    #   configuration: "Debug",
    #   export_method: "development",
    #   skip_package_ipa: true,
    #   skip_codesigning: true,
    #   derived_data_path: "derived_data",
    #   skip_package_dependencies_resolution: true
    #   )
    
    scan(
      scheme: "PIA VPN dev", 
      skip_build: false,
      build_for_testing: true,
      derived_data_path: "derived_data"
      )
    run_tests(
      scheme: "PIA VPN dev",
      testplan: "PIA-VPN-e2e-simulator",
      devices: ["iPhone 14"],
      prelaunch_simulator: true,
      test_without_building: true,
      derived_data_path: "derived_data"
    )
  end

  lane :tvos_e2e_tests do
    # build_app(
    #   scheme: "PIA VPN-tvOS", 
    #   skip_archive: true,
    #   skip_codesigning: true,
    #   configuration: "Debug",
    #   export_method: "development",
    #   skip_package_ipa: true,
    #   xcargs: "'platform=tvOS Simulator,name=Apple TV'",
      
    #   )

    scan(
      scheme: "PIA VPN-tvOS", 
      skip_build: false,
      build_for_testing: true,
      derived_data_path: "derived_data"
      )
    
    run_tests(
      scheme: "PIA VPN-tvOS",
      testplan: "PIA VPN-tvOS_E2E_Tests",
      test_without_building: true,
      prelaunch_simulator: true,
      device: "Apple TV",
      derived_data_path: "derived_data"
    )
  end

  desc "This line is for settin up the certificates and provisioning profiles for iOS"
  lane :get_profiles do |options|
    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content
    )

    certificates
    development_profiles = options[:development] || false

    prov_name_preffix = "match AppStore"
    if development_profiles == true
      prov_name_preffix = "match Development"
    end
    get_provisioning_profile(
      development: development_profiles,
      api_key: api_key,
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN",
      provisioning_name: "#{prov_name_preffix} com.privateinternetaccess.ios.PIA-VPN",
      fail_on_name_taken: true
    )

    get_provisioning_profile(
      development: development_profiles,
      api_key: api_key,
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN.Tunnel",
      provisioning_name: "#{prov_name_preffix} com.privateinternetaccess.ios.PIA-VPN.Tunnel",
      fail_on_name_taken: true
    )


    get_provisioning_profile(
      development: development_profiles,
      api_key: api_key,
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN.WG-Tunnel",
      provisioning_name: "#{prov_name_preffix} com.privateinternetaccess.ios.PIA-VPN.WG-Tunnel",
      fail_on_name_taken: true
    )

    get_provisioning_profile(
      development: development_profiles,
      api_key: api_key,
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN.PIAWidget",
      provisioning_name: "#{prov_name_preffix} com.privateinternetaccess.ios.PIA-VPN.PIAWidget",
      fail_on_name_taken: true
    )

    get_provisioning_profile(
      development: development_profiles,
      api_key: api_key,
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN.AdBlocker",
      provisioning_name: "#{prov_name_preffix} com.privateinternetaccess.ios.PIA-VPN.AdBlocker",
      fail_on_name_taken: true
    )

  end

  desc "This line is for setting up the certificates and provisioning profiles for tvOS"
  lane :get_tvos_profiles do

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content
    )

    certificates

    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN",
      provisioning_name: "PIA Distribution tvOS",
      platform: "tvos",
      fail_on_name_taken: true
    )

    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN.PacketTunnel",
      provisioning_name: "PIA Distribution tvOS PacketTunnel",
      platform: "tvos",
      fail_on_name_taken: true
    )
  end

  desc "This line is for setting up the certificates and provisioning profiles for development builds"
  lane :get_development_profiles do
    get_profiles(development: true)
  end

  desc "This line is for creating testflight build"
  lane :testflight_build do
    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content
    )

    increment_build_number_testflight

    build_app(scheme: "PIA VPN",
      export_method: "app-store",
      clean: true,
      export_options: {
        provisioningProfiles: { 
          "com.privateinternetaccess.ios.PIA-VPN" => "match AppStore com.privateinternetaccess.ios.PIA-VPN",
          "com.privateinternetaccess.ios.PIA-VPN.Tunnel" => "match AppStore com.privateinternetaccess.ios.PIA-VPN.Tunnel",
          "com.privateinternetaccess.ios.PIA-VPN.WG-Tunnel" => "match AppStore com.privateinternetaccess.ios.PIA-VPN.WG-Tunnel",
          "com.privateinternetaccess.ios.PIA-VPN.PIAWidget" => "match AppStore com.privateinternetaccess.ios.PIA-VPN.PIAWidget",
          "com.privateinternetaccess.ios.PIA-VPN.AdBlocker" => "match AppStore com.privateinternetaccess.ios.PIA-VPN.AdBlocker"
        }
      }
    )

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

  end

  desc "Match certificates for app store"
  lane :certificates do
    import_certificates
  end

  desc "This line is for creating a developer build"
  lane :development_build do

    current_branch = git_branch()
    commit_hash = last_git_commit()
    short_hash = commit_hash[:abbreviated_commit_hash]
    archive_path = "PIA_VPN_iOS.#{current_branch}_#{short_hash}"
    archive_zip_name = "#{archive_path}.zip"

    build_app(scheme: "PIA VPN",
      export_method: "development",
      clean: true,
      configuration: "Debug",
      build_path: "build/#{archive_path}",
      output_name: "#{archive_path}.ipa",
      export_options: {
        provisioningProfiles: { 
          "com.privateinternetaccess.ios.PIA-VPN" => "match Development com.privateinternetaccess.ios.PIA-VPN",
          "com.privateinternetaccess.ios.PIA-VPN.Tunnel" => "match Development com.privateinternetaccess.ios.PIA-VPN.Tunnel",
          "com.privateinternetaccess.ios.PIA-VPN.WG-Tunnel" => "match Development com.privateinternetaccess.ios.PIA-VPN.WG-Tunnel",
          "com.privateinternetaccess.ios.PIA-VPN.PIAWidget" => "match Development com.privateinternetaccess.ios.PIA-VPN.PIAWidget",
          "com.privateinternetaccess.ios.PIA-VPN.AdBlocker" => "match Development com.privateinternetaccess.ios.PIA-VPN.AdBlocker"
        }
      }
    )

    zip(output_path: archive_zip_name, path: "#{archive_path}.ipa")
    sh "mv ../#{archive_zip_name} ../artifacts/#{archive_zip_name}"

  end


  desc "Increase build number for TestFlight"
  private_lane :increment_build_number_testflight do 
    build_number = latest_testflight_build_number(
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN"
    )
    increment_build_number(
      build_number: build_number + 1 
    )
  end
end

desc "This line is for creating testflight build for tvOS"
  lane :testflight_build_tvos do
    
    key_id = ENV['APP_STORE_CONNECT_KEY_ID']
    issuer_id = ENV['APP_STORE_CONNECT_ISSUER_ID']
    key_content = ENV['APP_STORE_CONNECT_KEY']

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content
    )

    build_number = latest_testflight_build_number(
      app_identifier: "com.privateinternetaccess.ios.PIA-VPN",
      platform: "appletvos"
    )
    increment_build_number(
      build_number: build_number + 1 
    )

    build_app(scheme: "PIA VPN-tvOS",
      export_method: "app-store",
      xcargs: "-destination 'platform=tvOS'",
      clean: true,
      export_options: {
        provisioningProfiles: { 
          "com.privateinternetaccess.ios.PIA-VPN" => "PIA Distribution tvOS",
          "com.privateinternetaccess.ios.PIA-VPN.PacketTunnel" => "PIA Distribution tvOS PacketTunnel"
        }
      }
    )

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      app_platform: "appletvos"
    )

  end