# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.80.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  # main actions
  import "ci/clean_openssl.rb"
  import "ci/unit_test.rb"
  import "ci/create_archive.rb"
  import "ci/qa_deploy.rb"
  import "ci/qa_notify.rb"
  import "ci/beta_deploy.rb"
  import "ci/local/qa_bootstrap.rb"
  import "ci/local/push_build_tag.rb"

  import "test/try_build_number.rb"
  import "test/try_ipa.rb"
  import "test/try_qa_changelog.rb"
  import "test/try_beta_changelog.rb"
  import "test/try_serialize.rb"
  import "test/try_deserialize.rb"

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
