# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6 Plus",
  "iPad Pro (12.9 inch)"
])

languages([
  'en-US',
  #'de-DE',
  #'es-MX',
  #'fr-FR',
  #'it',
  #'ja',
  #'ko',
  #'no',
  #'pt-BR',
  #'ru',
  #'tr'
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "PIA VPN"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

#clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
